import { PageHeader } from "../components/common/Primitives";
import { MarketingHeader } from "../components/layout/MarketingHeader";

// #345 — standard privacy/GDPR policy page. Publicly accessible (no
// RequireAuth on its route in App.jsx) since a privacy policy has to be
// readable before someone creates an account, not just after — the
// footer link that points here (#337) shows on every page regardless of
// login state, so this has to work for both.
//
// Content below is standard-shape placeholder copy (data collected,
// cookies, learner rights, retention, contact) suitable for a
// prototype/demo. It isn't a substitute for real legal review before
// this app handles real user data — swap in reviewed copy once that
// happens.
const SECTIONS = [
  {
    title: "Overview",
    body: "This policy explains what personal data Keystone Learning collects, why, and what control you have over it. It applies to every learner, trainer, and provider account on this platform.",
  },
  {
    title: "Data we collect",
    body: "Account details you provide directly (name, email, password — stored and verified through our authentication provider, never in plain text), plus data generated by using the platform: course enrollments and progress, quiz submissions and scores, forum posts and notes, and activity used to calculate streaks, points, and leaderboard standing.",
  },
  {
    title: "Cookies",
    body: "We use only the cookies/local storage required to keep you signed in and remember basic preferences (like your daily goal or leaderboard opt-in). We don't use third-party advertising or tracking cookies.",
  },
  {
    title: "How we use your data",
    body: "To run the core product: enrolling you in courses, tracking progress and grades, issuing certificates, and powering features you opt into (like the leaderboard). We don't sell personal data to third parties.",
  },
  {
    title: "Your rights",
    body: "You can request a copy of the personal data we hold about you, ask us to correct inaccurate data, or request deletion of your account and associated data. You can also opt out of specific features (such as the leaderboard) at any time from Account settings.",
  },
  {
    title: "Data retention",
    body: "We retain account and progress data for as long as your account is active. If you request deletion, we remove your personal data within a reasonable period, except where we're required to retain limited records for legal or security reasons.",
  },
  {
    title: "Contact",
    body: "For any data request, question, or concern about this policy, contact us at privacy@keystonelearning.example.",
  },
];

export function PrivacyScreen({ loggedIn, onGo, onAuth }) {
  return (
    <div className="ks-page-enter">
      {!loggedIn && <MarketingHeader onGo={onGo} onAuth={onAuth} />}
      {/* Narrower than most pages (760 base, same as the course/path
          editors) — this is a reading page, not a grid of cards, so a
          tighter line length is more legible than the app's wider
          content pages.
          Viewport-fit pass — trimmed top/bottom padding (was 36/60) and
          the gap between sections (was 26, headings 6) so a laptop-height
          screen has the best shot at this + the footer fitting under one
          viewport without scrolling. Seven real sections of body copy
          still won't always fit on shorter screens no matter how tight
          the spacing gets — that's fine; the goal here was closing the
          gap, not forcing it at the cost of cramming a legal page. */}
      <div className="ks-page-scaled" style={{ "--ks-page-base": "760px", padding: "28px 28px 40px" }}>
        {/* #364 — title only kept logged out (AppTopbar already shows
            "Privacy & GDPR" for logged-in visitors, but there's no
            topbar at all when logged out); subtitle stays either way. */}
        <PageHeader
          title={loggedIn ? undefined : "Privacy & GDPR"}
          subtitle="Last updated August 2026."
        />
        {SECTIONS.map((s) => (
          <div key={s.title} style={{ marginBottom: 20 }}>
            <div style={{ fontSize: 15, fontWeight: 600, marginBottom: 4 }}>{s.title}</div>
            <div style={{ fontSize: 13.5, color: "var(--slate)", lineHeight: 1.6 }}>{s.body}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
